### ISSUE TITLE
i have question for image Array

### ISSUE THREAD

**Issue by kimseungmin** [aroldanm/ASCustomBannerView#3]
it says download images from Url  can use it

but there are error from nil..

i try it
let imageName = ["http://git..../a.png"]

but isn't work 
how can i use about it

**Comment by aroldanm** [comment]
First download the images from a URL, example:
      `let requestURL: NSURL = NSURL(string: url)!`
       `let urlRequest: NSMutableURLRequest = NSMutableURLRequest(url: requestURL as URL,     cachePolicy: .reloadIgnoringLocalAndRemoteCacheData, timeoutInterval: 5)`
        `let session = URLSession.shared`
       ` let task = session.dataTask(with: urlRequest as URLRequest) {
            (data, response, error) -> Void in etc...`
        

Second you have to save the images in UIImage array, example:
`let image = UIImage(data: try NSData(contentsOf: NSURL(string:item["image"]!) as! URL) as Data)`
`self.imageArray.append(image!)`

To finish you have create banner object and pass the array:
`self.bannerView.createBanner(imagesArray: imageArray, urlArray: urlArray)`

**Comment by kimseungmin** [comment]
thank you for reply :) 
may ask you by alamofire?

here is my code

Alamofire.request(api, method: .post, parameters: params, encoding: URLEncoding.default) .responseJSON { response in
            
            let swiftyJsonVar = JSON(response.result.value!)
            
                        print(swiftyJsonVar)
            
            if let items = swiftyJsonVar["ad_banner"].array {
                for item in items {
                    if let url = item["URL"].string {
                        
                        
                        NetInfo.urlString.append(url)
                        print(NetInfo.urlString)
                    }
                    
                    if let banner = item["IMG"].string {
}
//you create array of type UIImage
        var arrayImages = [UIImage]()
        for i in 0 ... imageName.count-1
        {
            arrayImages.append(UIImage(named: imageName[i])!)
        }
        
        //instance the class BannerView
        bannerView.createBanner(imagesArray: arrayImages, urlArray: urlString)
