### ISSUE TITLE
load images from remote URL? 

### ISSUE THREAD

**Issue by PrakashMaharjan** [aroldanm/ASCustomBannerView#4]
is it possible to display images from URL?

**Comment by aroldanm** [comment]
Hello PrakashMaharjan,
First you have download the image and then create the UIImage array. For finish you need instanciate my library sending the array of UIImage.

I do it this way:
1. Get JSON from URL
2. Get image from URL's image: 
let image = UIImage(data: try NSData(contentsOf: NSURL(string:"urlImageHere") as! URL) as Data)
3. I add the image in to array:
self.imageArrayBanner.append(image!)
4. I use this banner in a static cell in tableview then:
cell.bannerViewObject?.createBanner(imagesArray: imageArrayBanner, urlArray: urlArrayBanner)

you can see my implementation in the menu of this app ->  https://appsto.re/es/EnZBcb.i

sorry for my English. I hope I've helped

**Comment by PrakashMaharjan** [comment]
Thanks aroldanm for the reply.
